#!/usr/bin/env python3
"""Turns raw pty captures into src/data/scenes.ts.

The ANSI escapes are kept verbatim: the site parses them, so what the page
renders is the CLI's own colouring rather than a second opinion about it.
"""
import pathlib
import sys

# Order, labels and commands are the page's; the output is whatever ran.
SCENES = [
    (1, "Everything here reads fine to a human", "agsync check", "this is a real repo, anonymised"),
    (2, "Rarer than you'd think", "agsync check", "after someone fixed it"),
    (3, "Fourteen ways to be wrong", "agsync rules", None),
    (4, "Every commit you've ever pushed, judged", "agsync replay .", "the part that hurts"),
    (5, "How long nobody noticed", "agsync replay . --first-seen", None),
    (6, "The part people uninstall", 'git commit -m "wip"', "good luck"),
    (7, "Start from nothing", "agsync init", None),
]


def clean(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("\x04", "").replace("\x08", "")
    # script(1) on macOS echoes the EOF it sends as a literal "^D".
    if text.startswith("^D"):
        text = text[2:]
    # replay draws a progress line and erases it with ESC[K; keep what survived.
    if "\x1b[K" in text:
        text = text.split("\x1b[K", 1)[1]
    return text.strip("\n")


def ts(value: str) -> str:
    return (
        '"'
        + value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\x1b", "\\u001b")
        .replace("\n", "\\n")
        + '"'
    )


def main() -> None:
    raw, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    blocks = []
    for n, label, command, note in SCENES:
        body = clean((raw / f"{n}.out").read_text("utf-8", "replace"))
        status = (raw / f"{n}.status").read_text().strip() or "0"
        blocks.append(
            "  {\n"
            f"    n: {n},\n"
            f"    label: {ts(label)},\n"
            f"    command: {ts(command)},\n"
            f"    note: {ts(note) if note else 'null'},\n"
            f"    exit: {status},\n"
            f"    output: {ts(body)},\n"
            "  },"
        )

    out.write_text(
        "// Generated by scripts/capture-scenes.sh — do not edit by hand.\n"
        "// Every `output` below is what the command actually printed, ANSI included.\n\n"
        "export interface Scene {\n"
        "  n: number;\n"
        "  label: string;\n"
        "  command: string;\n"
        "  note: string | null;\n"
        "  exit: number;\n"
        "  output: string;\n"
        "}\n\n"
        "export const scenes: Scene[] = [\n" + "\n".join(blocks) + "\n];\n"
    )


if __name__ == "__main__":
    main()
