#!/usr/bin/env python3
"""Turns raw pty captures into src/data/scenes.ts.

The ANSI escapes are kept verbatim: the site parses them, so what the page
renders is the CLI's own colouring rather than a second opinion about it.
"""
import pathlib
import re
import sys

# id, the capture it comes from, the command as displayed, and the comment the
# page types after it. The displayed command is what was run, with one
# exception noted below.
SCENES = [
    ("install-uv", "install-uv",
     "uv tool install git+https://github.com/gabrielft-me/agsync", None),
    # Captured through a throwaway venv's pip so nothing lands on the machine
    # running this; pip does not print its own path, so the output is identical
    # to what the displayed command produces.
    ("install-pip", "install-pip",
     "pip install git+https://github.com/gabrielft-me/agsync", None),
    ("check-rot", "1", "agsync check", "this is a real repo, anonymised"),
    ("check-clean", "2", "agsync check", "after someone fixed it"),
    ("rules", "3", "agsync rules", None),
    ("replay", "4", "agsync replay .", "the part that hurts"),
    ("first-seen", "5", "agsync replay . --first-seen", None),
    ("gate", "6", 'git commit -m "wip"', "good luck"),
    ("init", "7", "agsync init", None),
]

# uv warns that the temporary bin directory this script points it at is not on
# PATH. That is an artifact of capturing in isolation, not of the command.
ISOLATION_NOISE = re.compile(
    r"\nwarning: `[^`]*` is not on your PATH\..*$", re.S
)


def clean(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("\x04", "").replace("\x08", "")
    # script(1) on macOS echoes the EOF it sends as a literal "^D".
    if text.startswith("^D"):
        text = text[2:]
    # replay draws a progress line and erases it with ESC[K; keep what survived.
    if "\x1b[K" in text:
        text = text.split("\x1b[K", 1)[1]
    text = ISOLATION_NOISE.sub("", text)
    return text.strip("\n")


def ts(value: str) -> str:
    return (
        '"'
        + value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\x1b", "\\u001b")
        .replace("\n", "\\n")
        + '"'
    )


def main() -> None:
    raw, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    blocks = []
    for scene_id, capture, command, note in SCENES:
        body = clean((raw / f"{capture}.out").read_text("utf-8", "replace"))
        status = (raw / f"{capture}.status").read_text().strip() or "0"
        blocks.append(
            "  {\n"
            f"    id: {ts(scene_id)},\n"
            f"    command: {ts(command)},\n"
            f"    note: {ts(note) if note else 'null'},\n"
            f"    exit: {status},\n"
            f"    output: {ts(body)},\n"
            "  },"
        )

    out.write_text(
        "// Generated by scripts/capture-scenes.sh — do not edit by hand.\n"
        "// Every `output` below is what the command actually printed, ANSI included.\n\n"
        "export interface Scene {\n"
        "  id: string;\n"
        "  command: string;\n"
        "  note: string | null;\n"
        "  exit: number;\n"
        "  output: string;\n"
        "}\n\n"
        "export const scenes: Scene[] = [\n" + "\n".join(blocks) + "\n];\n\n"
        "export const byId = (id: string): Scene => {\n"
        "  const scene = scenes.find((s) => s.id === id);\n"
        "  if (!scene) throw new Error(`no captured scene \"${id}\"`);\n"
        "  return scene;\n"
        "};\n"
    )


if __name__ == "__main__":
    main()
